# Generated by Django 5.0.1 on 2024-01-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='used_in_recipes',
            field=models.IntegerField(default=0),
        ),
    ]
